### ISSUE TITLE
Update GitHub guide to modify commit message format

### ISSUE THREAD

**Issue by natoverse** [atsid/guides#34]
Specifically, to add parens around issue number, which works around any editors that see a leading hash as a comment.

**Comment by bmathews** [comment]
It might be worth linking/including the commit msg validation git hook Chris wrote and maybe even the related npm postinstall script (or use https://www.npmjs.com/package/git-hooks)? 

https://github.com/atsid/generator-ats-node-webapp/blob/08b1372cfdebbef1a38f7d1697dc3fe078b5e092/generators/skeleton/templates/scripts/git/hooks/commit-msg

**Comment by natoverse** [comment]
That's a great point - if they use the generator, they get it for free, otherwise they should know where to copy it from if they want a bit more strictness on the repo.
